# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='numberOfPeople',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
