# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0002_event_numberofpeople'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
