# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
