# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0007_joinedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[(1, 'movies'), (2, 'walks'), (3, 'sport'), (4, 'parties'), (5, 'drink')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
