# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0007_joinedevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='numberOfPeople',
            new_name='number_of_people',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='1960-01-11'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[(0, 'no type'), (1, 'movies'), (2, 'walks'), (3, 'sport'), (4, 'parties'), (5, 'drink')], default=0, max_length=1),
        ),
    ]
