# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0009_auto_20170416_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_of_people',
        ),
    ]
