# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0010_remove_event_number_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_people',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
