# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0011_event_number_of_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='phone',
        ),
    ]
