# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enjoyly', '0012_remove_event_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[(0, 'male'), (1, 'female')], max_length=1)),
                ('age', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
