# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0013_anotheruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotheruser',
            name='age',
        ),
        migrations.AddField(
            model_name='anotheruser',
            name='birthday',
            field=models.DateField(default='1960-01-11'),
        ),
    ]
