# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0014_auto_20170416_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longtitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
