# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0015_auto_20170416_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotheruser',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longtitude',
            field=models.FloatField(blank=True),
        ),
    ]
