# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0016_auto_20170420_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[(0, 'no type'), (1, 'movies'), (2, 'walks'), (3, 'sport'), (4, 'parties'), (5, 'drink')], max_length=6),
        ),
    ]
