# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0018_auto_20170420_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotheruser',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6),
        ),
    ]
