# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0020_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default='1960-01-11'),
        ),
    ]
