# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjoyly', '0021_auto_20170420_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
